version: '2'

networks:
  suprboard:
    driver: bridge

services:
  app:
    image: php:8.1.19-fpm-alpine3.18
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    env_file:
      - app.env
    ports:
      - 8080:8080
    volumes:
      - .:/var/www

  postgresql:
    image: docker.io/bitnami/postgresql:15
    networks:
      - suprboard
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    env_file:
      - db.env

volumes:
  postgresql_data:
    driver: local